### ISSUE TITLE
some more bugs

### ISSUE THREAD

**Issue by ahhh** [ismailtasdelen/reverse-shell-cheatsheet#4]
Those encoding issues are in a bunch of examples:
#https://github.com/ismailtasdelen/reverse-shell-cheatsheet/blame/master/README.md#L40
#https://github.com/ismailtasdelen/reverse-shell-cheatsheet/blame/master/README.md#L46
#https://github.com/ismailtasdelen/reverse-shell-cheatsheet/blame/master/README.md#L53

**Comment by ahhh** [comment]
fixed em: https://github.com/ismailtasdelen/reverse-shell-cheatsheet/pull/5

**Comment by ismailtasdelen** [comment]
@ahhh ( Dan Borges ) Thanks dude, problem solved. 😉
